// <auto-generated />
using System;
using Game.ServerRunner.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Game.ServerRunner.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250826211521_Friedship")]
    partial class Friedship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Game.ServerRunner.Db.Model.DbAuthGuest", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("AuthGuest");
                });

            modelBuilder.Entity("Game.ServerRunner.Db.Model.DbFriendship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserA")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasComputedColumnSql("CASE WHEN \"RequesterId\" < \"AddresseeId\" THEN \"RequesterId\" ELSE \"AddresseeId\" END", true);

                    b.Property<Guid>("UserB")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasComputedColumnSql("CASE WHEN \"RequesterId\" > \"AddresseeId\" THEN \"RequesterId\" ELSE \"AddresseeId\" END", true);

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId", "Status");

                    b.HasIndex("RequesterId", "Status");

                    b.HasIndex("UserA", "UserB")
                        .IsUnique();

                    b.ToTable("Friendships", null, t =>
                        {
                            t.HasCheckConstraint("CK_Friendship_NotSelf", "\"RequesterId\" <> \"AddresseeId\"");
                        });
                });

            modelBuilder.Entity("Game.ServerRunner.Db.Model.DbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Game.ServerRunner.Db.Model.DbUserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("NickName")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Game.ServerRunner.Db.Model.DbAuthGuest", b =>
                {
                    b.HasOne("Game.ServerRunner.Db.Model.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Game.ServerRunner.Db.Model.DbFriendship", b =>
                {
                    b.HasOne("Game.ServerRunner.Db.Model.DbUser", null)
                        .WithMany()
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.ServerRunner.Db.Model.DbUser", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
